### ISSUE TITLE
Redis Timeout

### ISSUE THREAD

**Issue by javaadpatel** [AliBazzi/IdentityServer4.Contrib.RedisStore#21]
Is there a configuration settings that I am missing in order to optimize the latency of the redis cache. I am getting several timeout exceptions such as below:
``` 
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=3KiB, 5438ms elapsed, timeout is 5000ms), inst: 0, qu: 0, qs: 9, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/48-surge-identity-rc-shared-dev.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: 1E345CF0668B, IOCP: (Busy=0,Free=1000,Min=10,Max=1000), WORKER: (Busy=7,Free=32760,Min=50,Max=32767), v: 2.0.593.37019 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at IdentityServer4.Contrib.RedisStore.Stores.PersistedGrantStore.StoreAsync(PersistedGrant grant)
   at IdentityServer4.Stores.DefaultGrantStore`1.StoreItemAsync(String key, T item, String clientId, String subjectId, DateTime created, Nullable`1 expiration)
   at IdentityServer4.Stores.DefaultGrantStore`1.CreateItemAsync(T item, String clientId, String subjectId, DateTime created, Int32 lifetime)
   at IdentityServer4.Stores.DefaultRefreshTokenStore.StoreRefreshTokenAsync(RefreshToken refreshToken)
   at IdentityServer4.Services.DefaultRefreshTokenService.CreateRefreshTokenAsync(ClaimsPrincipal subject, Token accessToken, Client client)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.CreateAccessTokenAsync(ValidatedTokenRequest request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAuthorizationCodeRequestAsync(TokenRequestValidationResult request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

my configuration is:
```
 .AddOperationalStore(options =>
                {
                    options.RedisConnectionString = Configuration[RedisConfiguration.RedisConnection];
                    options.Db = 1;
                })
```

**Comment by javaadpatel** [comment]
I saw that there was a way to choose an existing connection to use, if the problem was due to trying to reconnect to redis, but it seems the options to set the connection multiplexer is deprecated in the newest version? 
![image](https://user-images.githubusercontent.com/22832462/59430869-aa8d7280-8de3-11e9-90b0-915b1739e492.png)

**Comment by javaadpatel** [comment]
I have changed to use the connection multiplexer property like:

```
  .AddOperationalStore(options =>
                {
                    options.RedisConnectionMultiplexer = RedisConnection;
                })
```

will need to test to see if this makes any difference to the timeouts

**Comment by javaadpatel** [comment]
executing SLOWLOG GET on the redis server these are the results, not sure if they have anything to do with this issue but just giving as much information as possible:
```
 1)    1)   "8"
  2)   "1560021564"
  3)   "16731"
  4)      1)    "ManagementCommand"
   2)    "list"


 2)    1)   "7"
  2)   "1559989011"
  3)   "17819"
  4)      1)    "ManagementCommand"
   2)    "list"


 3)    1)   "6"
  2)   "1559928308"
  3)   "12817"
  4)      1)    "ManagementCommand"
   2)    "list"


 4)    1)   "5"
  2)   "1559848194"
  3)   "11892"
  4)      1)    "ManagementCommand"
   2)    "list"


 5)    1)   "4"
  2)   "1559842168"
  3)   "15025"
  4)      1)    "ManagementCommand"
   2)    "?"
   3)    "-1"


 6)    1)   "3"
  2)   "1559841572"
  3)   "12425"
  4)      1)    "AUTH"
   2)    "DuCp7Hld1A2BENHDej5c80V31SNSVtbaHsz6P75gtrg="


 7)    1)   "2"
  2)   "1559841572"
  3)   "23122"
  4)      1)    "AUTH"
   2)    "DuCp7Hld1A2BENHDej5c80V31SNSVtbaHsz6P75gtrg="


 8)    1)   "1"
  2)   "1559841572"
  3)   "163203"
  4)      1)    "AUTH"
   2)    "DuCp7Hld1A2BENHDej5c80V31SNSVtbaHsz6P75gtrg="


 9)    1)   "0"
  2)   "1559841281"
  3)   "105828"
  4)      1)    "ManagementCommand"
   2)    "10.0.0.5"
   3)    "10224"
```

**Comment by AliBazzi** [comment]
Hi @javaadpatel 
First of all, by providing the ` SLOWLOG GET` you've exposed the authentication password for your instance, please rotate your key on the instance side, since you provided the instance dns and port in the exception dump

**Comment by javaadpatel** [comment]
That was my bad, deleted the post, will rotate the credentials shortly. Didn't realize that was the actual password for the instance, thank you for that.

**Comment by AliBazzi** [comment]
from the log above, I didn't find something useful that related to the library itself, it's good to checkout and double check the instance health + topology of your system, is Redis instance far from service that is hosting ?

Maybe you can change start from there and validate your solution, have you just started or it was working successfully and the problem started surfacing ?

**Comment by javaadpatel** [comment]
The redis instance is an Azure Redis Cache, located in the same region as the service fabric cluster accessing it. I checked the metrics on Azure and I can't see anything in particular from the server load, the cpu is nowhere near maxed out, same for memory.

I noticed the problem while testing that i was getting 404 error's and then when i checked application insights, i found the redis timeout exception.

**Comment by javaadpatel** [comment]
I am running identity server inside service fabric so there are multiple instances (one on each node) that will be accessing the redis cache for the grant, could that have any effect that causes this issue?

**Comment by AliBazzi** [comment]
I can't help beyond what I've commented up, sorry for that, this problem seems beyond the library.

**Comment by AliBazzi** [comment]
I will close the issue for now, and you can reopen it if you found out something that is related to the library itself.

**Comment by javaadpatel** [comment]
@AliBazzi , no problem, I think the problem has something to do with the library because the exception is coming from a method used in the library 
```IdentityServer4.Contrib.RedisStore.Stores.PersistedGrantStore.StoreAsync```
i'm wondering if it has to do with using redis for more than than just this library because I use it for both data protection and as a distributed cache in the application. If i find anything more I will re-open the issue, thank you for the help.

**Comment by javaadpatel** [comment]
@AliBazzi you were correct that it was nothing to do with the library, it was because I was using redis for storing the dataprotection key as well and so I had two connections to redis that were blocking each other at random times.

I changed my solution to use the same ConnectionMultiplexer wherever I was connecting to redis (ie. this library config and the data protector) and the timeout issues have dissappeared.
